### ISSUE TITLE
Fix profile card

### ISSUE THREAD

**Issue by Ananto30** [Ananto30/golpo-svelte#3]
## Task
![image](https://user-images.githubusercontent.com/15931537/135904879-5ceebc30-35ab-4b98-b107-744bde935b95.png)

Fix the profile card to have these two information -
- Work/Education
- Tagline
Remove all other info.

Please make it beautiful 😄

**Comment by Xaconi** [comment]
hey @Ananto30 can i work on this one?

**Comment by Ananto30** [comment]
Sure, assigned 👍
